- name: Update packages
  hosts: all
  become: yes
  become_method: sudo
  tasks:
     - name: Upgrade all packages to the latest version
       apt:
         name: {{name_packeges }}
           state: latest
