---
- name: Patching Kernel 
  hosts: all
  become: yes
  become_method: sudo
  tasks:
  - name: confirm kernel version
    shell: uname -a
    
  - name: Add repository
    yum_repository:
      name: Kernel
      description: EPEL YUM repo
      baseurl: http://mirror.centos.org/centos/7/os/x86_64/Packages/abrt-addon-kerneloops-2.1.11-52.el7.centos.x86_64.rpm
      state: absent

  - name: install updates
    yum: name="*" state=latest

  - name: confirm kernel version
    shell: uname -a
    register: kernel_version
  - debug: var=kernel_version.stdout
